# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c471298ef09ca1dc645c8aa5e891b90fa208b5be75e37ce92ca328ffaf9fd9db5b25dfbdb5bd0f447d28039024ada187eff4bd0a7b85ab066b98e2bd9b5785

test:
  secret_key_base: fe7753795f3dc8dc636ecb7455051646dc4b1adb2e8b71be304fa25597b6df25b5877052a32feb5c806857f8e1cfcc6b3b2fa0008fafa1f7bafc7e26aa8d79f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
